hl.config({
    autogenerated = 0,
    misc = {
        disable_hyprland_logo = true,
        mouse_move_enables_dpms = true,
    },
})

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
-- hl.gesture({ fingers = 3, direction = "down", mods = "ALT", action = "close" })
-- hl.gesture({ fingers = 3, direction = "up", action = 'overview:toggle'})
-- hl.gesture({ fingers = 3, direction = "left", scale = 1.5, action = "float" })